// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTextCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyTextCollection'](arg1, arg2, arg3);
}

export function ExportEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportEntry'](arg1, arg2, arg3, arg4);
}

export function ExportStrings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportStrings'](arg1, arg2, arg3, arg4);
}

export function GetGameFilesLocation() {
  return window['go']['main']['App']['GetGameFilesLocation']();
}

export function GetMetadata(arg1) {
  return window['go']['main']['App']['GetMetadata'](arg1);
}

export function GetTextCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTextCollection'](arg1, arg2, arg3);
}

export function GetTextEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTextEntry'](arg1, arg2, arg3);
}

export function GetTranslateLocation() {
  return window['go']['main']['App']['GetTranslateLocation']();
}

export function ImportEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportEntry'](arg1, arg2, arg3);
}

export function ListLanguages() {
  return window['go']['main']['App']['ListLanguages']();
}

export function ListTextEntries(arg1, arg2) {
  return window['go']['main']['App']['ListTextEntries'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadFileAsString(arg1) {
  return window['go']['main']['App']['ReadFileAsString'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SetUnsavedEdits(arg1) {
  return window['go']['main']['App']['SetUnsavedEdits'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
