// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spira} from '../models';

export function BuildTree():Promise<Array<spira.TreeNode>>;
