// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {interactions} from '../models';

export function Compress(arg1:interactions.GameDataInfo):Promise<void>;
