// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {interfaces} from '../models';
import {locations} from '../models';

export function Compress(arg1:interfaces.ISource,arg2:locations.IDestination):Promise<void>;
