// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function Compress(arg1:lib.FileInfo):Promise<void>;
