// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spira} from '../models';
import {common} from '../models';
import {dto} from '../models';
import {services} from '../models';

export function BuildTree():Promise<Array<spira.TreeNode>>;

export function Compress(arg1:string):Promise<void>;

export function ExportStrings(arg1:string,arg2:common.GameVersion,arg3:Array<string>,arg4:Array<string>):Promise<Array<string>>;

export function Extract(arg1:string):Promise<void>;

export function GetGameFilesLocation():Promise<string>;

export function GetMetadata(arg1:string):Promise<dto.Metadata>;

export function GetTextCollection(arg1:string,arg2:common.GameVersion,arg3:Array<string>):Promise<dto.Collection>;

export function GetTextEntry(arg1:string,arg2:string,arg3:common.GameVersion):Promise<dto.FileEntry>;

export function GetTranslateLocation():Promise<string>;

export function ListLanguages():Promise<Array<common.Language>>;

export function ListTextEntries(arg1:string,arg2:common.GameVersion):Promise<Array<services.EntrySummary>>;

export function ReadFileAsString(arg1:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
