// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildTree() {
  return window['go']['main']['App']['BuildTree']();
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function Extract(arg1) {
  return window['go']['main']['App']['Extract'](arg1);
}

export function ReadFileAsString(arg1) {
  return window['go']['main']['App']['ReadFileAsString'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTextFile'](arg1, arg2);
}
