// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadFileAsString(arg1:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
