// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {spira} from '../models';

export function BuildTree():Promise<Array<spira.TreeNode>>;

export function Compress(arg1:string):Promise<void>;

export function Extract(arg1:string):Promise<void>;

export function ReadFileAsString(arg1:string):Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
